### PR TITLE
Update to latest merlin (4.7)

### PR DESCRIPTION
**Pull request by ulugbekna**
How the rebase was performed: 

1. drops https://github.com/rgrinberg/merlin/commit/1385c29fd9d0b825bee3778fa69866693098685b because it causes rebase conflict
2. rebases rgrinberg/merlin#master on ocaml/merlin#master
3. drops 9b0f538f47fbf1b7337f99842c31b5e060b38aaf because it's now implemented in ocaml-lsp
4. re-do https://github.com/rgrinberg/merlin/commit/1385c29fd9d0b825bee3778fa69866693098685b: change `src/ocaml/preprocess/dune` back as it was in https://github.com/rgrinberg/merlin/commit/1385c29fd9d0b825bee3778fa69866693098685b, build, and commit all changes

### CODE REVIEW

**Comment by rgrinberg** [comment]
@voodoos did you upstream this commit? https://github.com/rgrinberg/merlin/pull/20/commits/9411ed0946a53a92b50bed95368bac4f3350be12

**Comment by rgrinberg** [comment]
@ulugbekna https://github.com/rgrinberg/merlin/pull/20/commits/3d995047ad5caaeea34e1001ebed5f4330d1f46c

why does this commit touch the menhir files?

**Comment by voodoos** [comment]
> @voodoos did you upstream this commit? [9411ed0](https://github.com/rgrinberg/merlin/commit/9411ed0946a53a92b50bed95368bac4f3350be12)

No, I was looking at the `lsp` branch when doing the upstreaming. Is the `master` branch the one you use now ?

**Comment by ulugbekna** [comment]
> No, I was looking at the lsp branch when doing the upstreaming. Is the master branch the one you use now ?

yes

**Comment by voodoos** [comment]
@rgrinberg, could you describe to the advantages of using `spawn` in [25a9acd](https://github.com/rgrinberg/merlin/pull/20/commits/25a9acdb10194b6cf775aa1e5d4ba1079b8bd9b2) ? Would there be an alternative way to achieve the benefits ?

**Comment by ulugbekna** [comment]
> why does this commit touch the menhir files?

But so does 1385c29fd9d0b825bee3778fa69866693098685b, doesn't it? I just followed the suite

**Comment by voodoos** [comment]
> > why does this commit touch the menhir files?
> 
> But so does [1385c29](https://github.com/rgrinberg/merlin/commit/1385c29fd9d0b825bee3778fa69866693098685b), doesn't it? I just followed the suite

Since there are no changes to the parser that require an update of the embedded `menhirLib` you can just remove these changes.

**Comment by rgrinberg** [comment]
> could you describe to the advantages of using spawn in [25a9acd](https://github.com/rgrinberg/merlin/pull/20/commits/25a9acdb10194b6cf775aa1e5d4ba1079b8bd9b2) ? Would there be an alternative way to achieve the benefits ?

Sure:

1. It's faster because it uses vfork when available
2. It has better error reporting on failure
3. It allows you to set the cwd

I might starting using other features it provides as well when I'll run ppx in lsp directly.

**Comment by rgrinberg** [comment]
> > why does this commit touch the menhir files?
> 
> But so does [1385c29](https://github.com/rgrinberg/merlin/commit/1385c29fd9d0b825bee3778fa69866693098685b), doesn't it? I just followed the suite

That was a mistake. The changes aren't needed and we can drop them

**Comment by ulugbekna** [comment]
The parser changes problem should be fixed

**Comment by rgrinberg** [comment]
Thanks. Updated the master branch

**Pull request closed without merging**
