### PR TITLE
Update to latest merlin

### PR DESCRIPTION
**Pull request by ulugbekna**
The goal of this work is to add initial support for `Construct` command (recently merged in https://github.com/ocaml/merlin/pull/1318) in ocaml-lsp as requested by trefis. 

I hope I'm doing the update the right way: I rebased `rgrinberg/merlin#lsp` on `ocaml/merlin#master`. 

The tests in ocaml-lsp are passing when vendoring this version of merlin. However, when I run merlin tests (`make test`) in this branch, I get 

```
Error: Dependency cycle between the following files:
   _build/.aliases/default/.dot-merlin-reader-files-00000000000000000000000000000000
-> _build/.aliases/default/.merlin-files-00000000000000000000000000000000
-> _build/.aliases/default/.dot-merlin-reader-files-00000000000000000000000000000000
make: *** [test] Error 1
```

I get this in the `lsp` branch without my patch as well, so that shouldn't be a problem? 

Possibly we could also include here https://github.com/ocaml/merlin/pull/1353/, https://github.com/ocaml/merlin/pull/1313/, https://github.com/ocaml/merlin/pull/1314/, and https://github.com/ocaml/merlin/pull/1339. Wdyt?

### CODE REVIEW

**Comment by ulugbekna** [comment]
@rgrinberg a friendly ping in case you missed the PR notification or just forgot about it

**Comment by rgrinberg** [comment]
>  a friendly ping in case you missed the PR notification or just forgot about it

Thanks, I indeed missed it.

> However, when I run merlin tests (make test) in this branch, I get

Seems like a dune bug to me.

**Comment by rgrinberg** [comment]
Rebased and pushed.

**Comment by rgrinberg** [comment]
As for the patches, the 1st has already been merged. For the next two, let's give Thomas or Ulysse one last more chance to review and merge. Otherwise, we'll include them in 1.7.0. The last patch needs at least one pair of eyes from a maintainer to verify its sanity. I'll try and get on that this week.

**Pull request closed without merging**
